In [4]:
import itertools as it

#C1 - C2 - C4 - C6
X = {0, 18}
Y = {0, 40}
Z = {0, 9}
set(it.product(X, Y, Z))

{(0, 0, 0),
 (0, 0, 9),
 (0, 40, 0),
 (0, 40, 9),
 (18, 0, 0),
 (18, 0, 9),
 (18, 40, 0),
 (18, 40, 9)}

In [6]:
import itertools as it

#C1 - C2 - C4 - C5 - C6
X = {0, 18}
Y = {0, 40}
Z = {0, 12}
M = {0, 36}
set(it.product(X, Y, Z, M))

{(0, 0, 0, 0),
 (0, 0, 0, 36),
 (0, 0, 12, 0),
 (0, 0, 12, 36),
 (0, 40, 0, 0),
 (0, 40, 0, 36),
 (0, 40, 12, 0),
 (0, 40, 12, 36),
 (18, 0, 0, 0),
 (18, 0, 0, 36),
 (18, 0, 12, 0),
 (18, 0, 12, 36),
 (18, 40, 0, 0),
 (18, 40, 0, 36),
 (18, 40, 12, 0),
 (18, 40, 12, 36)}

In [1]:
import itertools as it

#C1 - C2 - C4 - C3 - C5 - C6
X = {0, 18}
Y = {0, 40}
Z = {0, 12}
M = {0, 12}
N = {0, 36}
set(it.product(X, Y, Z, M, N))

{(0, 0, 0, 0, 0),
 (0, 0, 0, 0, 36),
 (0, 0, 0, 12, 0),
 (0, 0, 0, 12, 36),
 (0, 0, 12, 0, 0),
 (0, 0, 12, 0, 36),
 (0, 0, 12, 12, 0),
 (0, 0, 12, 12, 36),
 (0, 40, 0, 0, 0),
 (0, 40, 0, 0, 36),
 (0, 40, 0, 12, 0),
 (0, 40, 0, 12, 36),
 (0, 40, 12, 0, 0),
 (0, 40, 12, 0, 36),
 (0, 40, 12, 12, 0),
 (0, 40, 12, 12, 36),
 (18, 0, 0, 0, 0),
 (18, 0, 0, 0, 36),
 (18, 0, 0, 12, 0),
 (18, 0, 0, 12, 36),
 (18, 0, 12, 0, 0),
 (18, 0, 12, 0, 36),
 (18, 0, 12, 12, 0),
 (18, 0, 12, 12, 36),
 (18, 40, 0, 0, 0),
 (18, 40, 0, 0, 36),
 (18, 40, 0, 12, 0),
 (18, 40, 0, 12, 36),
 (18, 40, 12, 0, 0),
 (18, 40, 12, 0, 36),
 (18, 40, 12, 12, 0),
 (18, 40, 12, 12, 36)}

In [2]:
import itertools as it

#C1 - C2 - C3 - C4 - C5 - C6
X = {0, 18}
Y = {0, 8}
Z = {0, 12}
M = {0, 12}
N = {0, 36}
set(it.product(X, Y, Z, M, N))

{(0, 0, 0, 0, 0),
 (0, 0, 0, 0, 36),
 (0, 0, 0, 12, 0),
 (0, 0, 0, 12, 36),
 (0, 0, 12, 0, 0),
 (0, 0, 12, 0, 36),
 (0, 0, 12, 12, 0),
 (0, 0, 12, 12, 36),
 (0, 8, 0, 0, 0),
 (0, 8, 0, 0, 36),
 (0, 8, 0, 12, 0),
 (0, 8, 0, 12, 36),
 (0, 8, 12, 0, 0),
 (0, 8, 12, 0, 36),
 (0, 8, 12, 12, 0),
 (0, 8, 12, 12, 36),
 (18, 0, 0, 0, 0),
 (18, 0, 0, 0, 36),
 (18, 0, 0, 12, 0),
 (18, 0, 0, 12, 36),
 (18, 0, 12, 0, 0),
 (18, 0, 12, 0, 36),
 (18, 0, 12, 12, 0),
 (18, 0, 12, 12, 36),
 (18, 8, 0, 0, 0),
 (18, 8, 0, 0, 36),
 (18, 8, 0, 12, 0),
 (18, 8, 0, 12, 36),
 (18, 8, 12, 0, 0),
 (18, 8, 12, 0, 36),
 (18, 8, 12, 12, 0),
 (18, 8, 12, 12, 36)}

In [4]:
import itertools as it

#C1 - C2 - C3 - C5 - C6
X = {0, 18}
Y = {0, 8}
Z = {0, 12}
M = {0, 36}
set(it.product(X, Y, Z, M))

{(0, 0, 0, 0),
 (0, 0, 0, 36),
 (0, 0, 12, 0),
 (0, 0, 12, 36),
 (0, 8, 0, 0),
 (0, 8, 0, 36),
 (0, 8, 12, 0),
 (0, 8, 12, 36),
 (18, 0, 0, 0),
 (18, 0, 0, 36),
 (18, 0, 12, 0),
 (18, 0, 12, 36),
 (18, 8, 0, 0),
 (18, 8, 0, 36),
 (18, 8, 12, 0),
 (18, 8, 12, 36)}

In [7]:
import itertools as it

#C1 - C2 - C3 - C4 - C6 
X = {0, 18}
Y = {0, 8}
Z = {0, 12}
M = {0, 9}
set(it.product(X, Y, Z, M))

{(0, 0, 0, 0),
 (0, 0, 0, 9),
 (0, 0, 12, 0),
 (0, 0, 12, 9),
 (0, 8, 0, 0),
 (0, 8, 0, 9),
 (0, 8, 12, 0),
 (0, 8, 12, 9),
 (18, 0, 0, 0),
 (18, 0, 0, 9),
 (18, 0, 12, 0),
 (18, 0, 12, 9),
 (18, 8, 0, 0),
 (18, 8, 0, 9),
 (18, 8, 12, 0),
 (18, 8, 12, 9)}

In [8]:
import itertools as it

#C1 - C3 - C5 - C6 
X = {0, 9}
Y = {0, 12}
Z = {0, 36}
set(it.product(X, Y, Z))

{(0, 0, 0),
 (0, 0, 36),
 (0, 12, 0),
 (0, 12, 36),
 (9, 0, 0),
 (9, 0, 36),
 (9, 12, 0),
 (9, 12, 36)}

In [15]:
import itertools as it

#C1 - C3 - C4 - C5 - C6
X = {0, 9}
Y = {0, 12}
Z = {0, 12}
M = {0, 36}
set(it.product(X, Y, Z, M))

{(0, 0, 0, 0),
 (0, 0, 0, 36),
 (0, 0, 12, 0),
 (0, 0, 12, 36),
 (0, 12, 0, 0),
 (0, 12, 0, 36),
 (0, 12, 12, 0),
 (0, 12, 12, 36),
 (9, 0, 0, 0),
 (9, 0, 0, 36),
 (9, 0, 12, 0),
 (9, 0, 12, 36),
 (9, 12, 0, 0),
 (9, 12, 0, 36),
 (9, 12, 12, 0),
 (9, 12, 12, 36)}

In [10]:
import itertools as it

#C1 - C3 - C4 - C6
X = {0, 9}
Y = {0, 12}
Z = {0, 9}
set(it.product(X, Y, Z))

{(0, 0, 0),
 (0, 0, 9),
 (0, 12, 0),
 (0, 12, 9),
 (9, 0, 0),
 (9, 0, 9),
 (9, 12, 0),
 (9, 12, 9)}

In [11]:
import itertools as it

#C1 - C3 - C2 - C4 - C6
X = {0, 9}
Y = {0, 8}
Z = {0, 40}
M = {0, 9}
set(it.product(X, Y, Z, M))

{(0, 0, 0, 0),
 (0, 0, 0, 9),
 (0, 0, 40, 0),
 (0, 0, 40, 9),
 (0, 8, 0, 0),
 (0, 8, 0, 9),
 (0, 8, 40, 0),
 (0, 8, 40, 9),
 (9, 0, 0, 0),
 (9, 0, 0, 9),
 (9, 0, 40, 0),
 (9, 0, 40, 9),
 (9, 8, 0, 0),
 (9, 8, 0, 9),
 (9, 8, 40, 0),
 (9, 8, 40, 9)}

In [12]:
import itertools as it

#C1 - C3 - C2 - C4 - C5 - C6
X = {0, 9}
Y = {0, 8}
Z = {0, 40}
M = {0, 12}
N = {0, 36}
set(it.product(X, Y, Z, M, N))

{(0, 0, 0, 0, 0),
 (0, 0, 0, 0, 36),
 (0, 0, 0, 12, 0),
 (0, 0, 0, 12, 36),
 (0, 0, 40, 0, 0),
 (0, 0, 40, 0, 36),
 (0, 0, 40, 12, 0),
 (0, 0, 40, 12, 36),
 (0, 8, 0, 0, 0),
 (0, 8, 0, 0, 36),
 (0, 8, 0, 12, 0),
 (0, 8, 0, 12, 36),
 (0, 8, 40, 0, 0),
 (0, 8, 40, 0, 36),
 (0, 8, 40, 12, 0),
 (0, 8, 40, 12, 36),
 (9, 0, 0, 0, 0),
 (9, 0, 0, 0, 36),
 (9, 0, 0, 12, 0),
 (9, 0, 0, 12, 36),
 (9, 0, 40, 0, 0),
 (9, 0, 40, 0, 36),
 (9, 0, 40, 12, 0),
 (9, 0, 40, 12, 36),
 (9, 8, 0, 0, 0),
 (9, 8, 0, 0, 36),
 (9, 8, 0, 12, 0),
 (9, 8, 0, 12, 36),
 (9, 8, 40, 0, 0),
 (9, 8, 40, 0, 36),
 (9, 8, 40, 12, 0),
 (9, 8, 40, 12, 36)}

In [13]:
import itertools as it

#C1 - C3 - C5 - C4 - C6
X = {0, 9}
Y = {0, 12}
Z = {0, 12}
M = {0, 9}
set(it.product(X, Y, Z, M))

{(0, 0, 0, 0),
 (0, 0, 0, 9),
 (0, 0, 12, 0),
 (0, 0, 12, 9),
 (0, 12, 0, 0),
 (0, 12, 0, 9),
 (0, 12, 12, 0),
 (0, 12, 12, 9),
 (9, 0, 0, 0),
 (9, 0, 0, 9),
 (9, 0, 12, 0),
 (9, 0, 12, 9),
 (9, 12, 0, 0),
 (9, 12, 0, 9),
 (9, 12, 12, 0),
 (9, 12, 12, 9)}

In [14]:
import itertools as it

#C1 - C2 - C3 - C5 - C4 - C6
X = {0, 18}
Y = {0, 8}
Z = {0, 12}
M = {0, 12}
N = {0, 9}
set(it.product(X, Y, Z, M, N))

{(0, 0, 0, 0, 0),
 (0, 0, 0, 0, 9),
 (0, 0, 0, 12, 0),
 (0, 0, 0, 12, 9),
 (0, 0, 12, 0, 0),
 (0, 0, 12, 0, 9),
 (0, 0, 12, 12, 0),
 (0, 0, 12, 12, 9),
 (0, 8, 0, 0, 0),
 (0, 8, 0, 0, 9),
 (0, 8, 0, 12, 0),
 (0, 8, 0, 12, 9),
 (0, 8, 12, 0, 0),
 (0, 8, 12, 0, 9),
 (0, 8, 12, 12, 0),
 (0, 8, 12, 12, 9),
 (18, 0, 0, 0, 0),
 (18, 0, 0, 0, 9),
 (18, 0, 0, 12, 0),
 (18, 0, 0, 12, 9),
 (18, 0, 12, 0, 0),
 (18, 0, 12, 0, 9),
 (18, 0, 12, 12, 0),
 (18, 0, 12, 12, 9),
 (18, 8, 0, 0, 0),
 (18, 8, 0, 0, 9),
 (18, 8, 0, 12, 0),
 (18, 8, 0, 12, 9),
 (18, 8, 12, 0, 0),
 (18, 8, 12, 0, 9),
 (18, 8, 12, 12, 0),
 (18, 8, 12, 12, 9)}